const env = require('./env');

module.exports = [
  {
    path: '/api/v1/auth',
    target: env.services.auth,
    serviceName: 'auth',
    public: true,
    stripPrefix: false,
  },
  {
    path: '/api/v1/media/public',
    target: env.services.media,
    serviceName: 'media',
    public: true,
    stripPrefix: false,
  },
  {
    path: '/api/v1/users',
    target: env.services.user,
    serviceName: 'user',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/academics',
    target: env.services.academic,
    serviceName: 'academic',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/admissions',
    target: env.services.admission,
    serviceName: 'admission',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/enrollments',
    target: env.services.enrollment,
    serviceName: 'enrollment',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/content',
    target: env.services.content,
    serviceName: 'content',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/assessments',
    target: env.services.assessment,
    serviceName: 'assessment',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/examinations',
    target: env.services.examination,
    serviceName: 'examination',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/grades',
    target: env.services.grading,
    serviceName: 'grading',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/attendance',
    target: env.services.attendance,
    serviceName: 'attendance',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/timetable',
    target: env.services.timetable,
    serviceName: 'timetable',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/finance',
    target: env.services.finance,
    serviceName: 'finance',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/library',
    target: env.services.library,
    serviceName: 'library',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/hostel',
    target: env.services.hostel,
    serviceName: 'hostel',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/notifications',
    target: env.services.notification,
    serviceName: 'notification',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/forums',
    target: env.services.forum,
    serviceName: 'forum',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/live-classes',
    target: env.services.liveClass,
    serviceName: 'liveClass',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/documents',
    target: env.services.document,
    serviceName: 'document',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/reports',
    target: env.services.reporting,
    serviceName: 'reporting',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/media',
    target: env.services.media,
    serviceName: 'media',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/search',
    target: env.services.search,
    serviceName: 'search',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/audit',
    target: env.services.audit,
    serviceName: 'audit',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/calendar',
    target: env.services.calendar,
    serviceName: 'calendar',
    public: false,
    stripPrefix: false,
  },
  {
    path: '/api/v1/ai',
    target: env.services.aiRag,
    serviceName: 'aiRag',
    public: false,
    stripPrefix: false,
  }
];
